language: csharp
solution: ./SampleWebAPI.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./SampleWebAPI.sln

script:
  - xbuild ./SampleWebAPI.sln
  - nunit-console ./SampleWebAPITests/bin/Debug/SampleWebAPITests.dll

before_deploy:
  - gem update

deploy:
  - provider: azure_web_apps
