language: csharp
solution: "./SampleWebAPI.sln"
install:
- sudo apt-get install nunit-console
- nuget restore ./SampleWebAPI.sln
script:
- xbuild ./SampleWebAPI.sln
- nunit-console ./SampleWebAPITests/bin/Debug/SampleWebAPITests.dll
before_deploy:
- gem update
deploy:
- provider: azure_web_apps
env:
  global:
  - secure: kcTdySNoblokmmY150hkkzJVembwmGXN82iRp90/BwACMVzEJZh/mh1iT6acEDh86QR1liA33onBxG2mfVhytF3qy2Hx/9/oTYfNnOE2UpA634HzdhV6bywSwdQ1EpbFivlm8PTrT1SYLr51Nus3I0pYwTsUDYUuC8ArScOXCAVEKCO388BYobMsYSBK0y6RFuW79hyk5EQuRYOefigBia3Qj55Izi73KCH/DS/VCJdB59rEZz+4a2vAkqdOrzH4KC6g4HvWj2j4sukQSCv8jStw7T7vysNA4VPIYnXR0IxVBhsn9O5kz5YzIWOGb1Aog+7pNKj7x2Gm5Kk9bB6nWVe1ArMK+wSlTsV1vsw1wLu09QLLF+fBxjcyyCVUt8LDh8/EDnVfS51XNSzd8y47Tb8CaqOsPAJAD59+R0zFr46Y1A7OoAGFTAih2PW4zVi7cKML9RJAED3A5M0K3QxTAycoAUnA8F9kAHjbyaUQZwrvyssV/Rc4B3PrxQDoYpMkS+eJWqWtyxklgtpVp3OmTZM1nTDl6iTn2miTVwqiseAAttenj9TledfDGiy7aIvr+vcWfF14n8mHKD4UJ0sv3FdvtSp5RCfRs4DbKW6V6+igeMDISg/wfTROQyDNI6oMF6R8wOR2tX4Dn4PDoKI6/3A5Frm9uLkqwFebFhvYGmk=
