language: csharp
solution: "./SampleWebAPI.sln"
install:
- sudo apt-get install nunit-console
- nuget restore ./SampleWebAPI.sln
script:
- xbuild ./SampleWebAPI.sln
- nunit-console ./SampleWebAPITests/bin/Debug/SampleWebAPITests.dll
before_deploy:
- gem update
deploy:
- provider: azure_web_apps
env:
  global:
    - AZURE_WA_USERNAME: ci-git
    - AZURE_WA_SITE: precisionlender-simplewebapi
    - secure: qEmPtWlod2Ma4QhII+SFMMflhlRyyjpvfhr0epu9ha14l9yDqwE1qtAwb5RWUSh0efyxlvezwoqCbou4zbjPpto8UThrZULx1FVCcy5ZEsaT7y2OgKCZhLe3jeoGUD0/WTKU08O6o1AR+fSUmr97EhuQOWznnvBaj0KTPhCja2ZrzWRtW0LFm4ojG4QE0147Q3ZspOq2jCeu0S1MGOIPJ3GsmPFNTcgdFfsK/Gv5T9fa6ABE5MAdxi25qiRCaip2qDMPwN/sLtzG6mS7mt21ujM2Dx+1HfkZkZJ65HhgGNaRZH+Il2AbvWjtQEmnkP/BTkvdXr0ipLYvTBDvgKPA3vgUSBuUrLDJ2aMrgHla+Ly/Q+DhBv6jDbtycrSW3qp25EFW/TgBcZqfaNo2noZg91y8inVXk/+0HsEYtFWdtGCmVqRU05btxJQM8fZDWR84q7/rtfK5zCER/yxV9mrxCxyyaeSW82ddwYc1Wb4iHVvWS5l9q8e7o4pFl5LhGueibxpvIivtHREv+HbW7pVf/NvMNc6wZJWAxrDA4N3A+kaW11zuixacQa0sCG8TJ0mS3Ljc4y7O60x59GzGe2DbVcXMyJVzm5XRP5C/xEb9YpRIwUpHLSfOQoeTXSP7rsEb7N3AXg4V/Sf6RsFLNi/I4EoFISDwKnGzTL5sr840zr0=
